// Compiles tokens/tokens.json (W3C DTCG) into src/styles/tokens.css.
//
// Tier 1 (primitive)  -> raw custom properties        e.g. --color-neutral-25
// Tier 2 (semantic)   -> intent, references tier 1    e.g. --surface-canvas: var(--color-neutral-25)
// Tier 3 (component)  -> references tier 2            e.g. --card-bg: var(--surface-raised)
//
// References stay as var() chains instead of being flattened, so overriding a
// tier-2 token (dark mode, or a case-study theme) cascades to every component
// that consumes it. That is the same inheritance model as the white-label
// platform in case study 03.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const source = JSON.parse(readFileSync(resolve(root, "tokens/tokens.json"), "utf8"));
const outFile = resolve(root, "src/styles/tokens.css");

const TIERS = ["primitive", "semantic", "component"];

/** token path (with tier) -> css custom property name (tier dropped) */
const varName = (path) => "--" + path.split(".").slice(1).join("-");

const toCss = (value) => {
  if (Array.isArray(value)) return `cubic-bezier(${value.join(", ")})`;
  if (typeof value === "number") return String(value);
  return String(value).replace(/\{([^}]+)\}/g, (_, ref) => {
    if (!TIERS.includes(ref.split(".")[0])) throw new Error(`Unknown tier in reference {${ref}}`);
    return `var(${varName(ref)})`;
  });
};

/** Walk a tier and collect { path, value, dark } leaf tokens. */
function collect(node, path, out) {
  for (const [key, child] of Object.entries(node)) {
    if (key.startsWith("$")) continue;
    const p = `${path}.${key}`;
    if (child && typeof child === "object" && "$value" in child) {
      out.push({ path: p, value: child.$value, dark: child.$extensions?.mode?.dark });
    } else if (child && typeof child === "object") {
      collect(child, p, out);
    }
  }
  return out;
}

const tokens = Object.fromEntries(TIERS.map((t) => [t, collect(source[t], t, [])]));

// Validate every reference resolves to a declared token.
const declared = new Set(TIERS.flatMap((t) => tokens[t].map((x) => x.path)));
for (const t of TIERS) {
  for (const tok of tokens[t]) {
    for (const v of [tok.value, tok.dark].filter(Boolean)) {
      for (const [, ref] of String(v).matchAll(/\{([^}]+)\}/g)) {
        if (!declared.has(ref)) throw new Error(`${tok.path} references missing token {${ref}}`);
      }
    }
  }
}

const decl = (list, pick = "value", indent = "  ") =>
  list
    .filter((t) => t[pick] !== undefined)
    .map((t) => `${indent}${varName(t.path)}: ${toCss(t[pick])};`)
    .join("\n");

const darkSemantic = tokens.semantic.filter((t) => t.dark !== undefined);

// Themes: re-point the semantic accent group at another primitive palette.
const accentTokens = tokens.semantic.filter((t) => t.path.startsWith("semantic.accent."));
const themes = Object.entries(source.themes ?? {}).filter(([k]) => !k.startsWith("$"));
const swap = (v, palette) => (v === undefined ? v : String(v).replaceAll("primitive.color.ultramarine.", `primitive.color.${palette}.`));

const themeBlocks = themes
  .map(([name, { palette }]) => {
    const light = accentTokens.map((t) => ({ ...t, value: swap(t.value, palette) }));
    const dark = accentTokens.map((t) => ({ ...t, value: swap(t.dark ?? t.value, palette) }));
    return [
      `[data-accent="${name}"] {\n${decl(light)}\n}`,
      `:root[data-theme="dark"] [data-accent="${name}"] {\n${decl(dark)}\n}`,
    ].join("\n");
  })
  .join("\n\n");

const css = `/* ------------------------------------------------------------------
 * GENERATED by scripts/build-tokens.mjs from tokens/tokens.json.
 * Do not edit by hand: change the JSON and run \`npm run tokens\`.
 * ------------------------------------------------------------------ */

/* Tier 1 · primitive */
:root {
${decl(tokens.primitive)}
}

/* Tier 2 · semantic (light is the default mode) */
:root {
  color-scheme: light;
${decl(tokens.semantic)}
}

/* Tier 3 · component
 * Also declared on [data-accent] so var() chains re-resolve inside a themed
 * subtree (custom properties inherit their computed value, not the chain). */
:root {
${decl(tokens.component)}
}
[data-accent] {
${decl(tokens.semantic.filter((t) => String(t.value).includes("{semantic.")))}
${decl(tokens.component)}
}

/* Mode · dark. Light is the default for every first visit; dark applies
 * only when the visitor chooses it (the choice is remembered). */
:root[data-theme="dark"] {
  color-scheme: dark;
${decl(darkSemantic, "dark")}
}

/* Themes · per-case-study accents (override tier 2 only) */
${themeBlocks}
`;

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, css);
const count = TIERS.reduce((n, t) => n + tokens[t].length, 0);
console.log(`tokens: ${count} tokens (${TIERS.map((t) => `${tokens[t].length} ${t}`).join(", ")}), ${themes.length} themes -> src/styles/tokens.css`);
